version: 2.1

default_image: &default_image
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.6.0

default_filters: &default_filters
  filters:
    tags:
      only: /.*/
    branches:
      only: /.*/

version: 2
jobs:
  install:
    <<: *default_image
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .      
  format_check:
    <<: *default_image
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run format:check
  test:
    <<: *default_image
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test
  publish_npm:
    <<: *default_image
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install:
          <<: *default_filters
      - format_check:
          <<: *default_filters
          requires:
            - install
      - test:
          <<: *default_filters
          requires:
            - install
      - publish_npm:
          context: npm-user
          requires:
            - format_check
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/